-- migrate:up
INSERT INTO productos (id, descripcion, cuidados, propiedades, stock, tipo_id, color_id, tamano_id, imagen, precio) VALUES
    (1, 'Fluye Bottle 500 ml Manu', 
        'Hand wash only. Do not microwave.', 
        'Keeps beverages cold for 24 hours and hot for 12 hours. Made from stainless steel.', 
        50, 1, 1, 4, 'https://fluye-statics.s3.amazonaws.com/product_color/Cup_Pro_590_Manu_Logo.png', 89.00),
    (2, 'Fluye Bottle 500 ml White Marble', 
        'Hand wash only. Do not microwave.', 
        'Keeps beverages cold for 24 hours and hot for 12 hours. Made from stainless steel.', 
        50, 1, 2, 4, 'https://fluye-statics.s3.amazonaws.com/product_color/Bottle_500_White_Marble_Logo.png', 89.00),
    (3, 'Fluye Bottle 500 ml Producto Solidario CRM Yellow', 
        'Hand wash only. Do not microwave.', 
        'Keeps beverages cold for 24 hours and hot for 12 hours. Made from stainless steel.', 
        50, 1, 3, 4, 'https://fluye-statics.s3.amazonaws.com/product_color/Cassa_Ronald_Bottle500_Lima_3.png', 80.00),
    (4, 'Fluye Bottle 500 ml Producto Solidario CRM Blue', 
        'Hand wash only. Do not microwave.', 
        'Keeps beverages cold for 24 hours and hot for 12 hours. Made from stainless steel.', 
        50, 1, 4, 4, 'https://fluye-statics.s3.amazonaws.com/product_color/Cassa_Ronald_Bottle500_SkyBlue_1.png', 80.00),
    (5, 'Fluye Sport 700 ml Baja Sand', 
        'Dishwasher safe. Do not freeze.', 
        'Lightweight and durable. Made from BPA-free plastic.', 
        50, 2, 18, 8, 'https://fluye-statics.s3.amazonaws.com/product_color/Sport_Baja_Sand_700ml.png', 89.00),
    (6, 'Fluye Sport 700 ml Lila', 
        'Dishwasher safe. Do not freeze.', 
        'Lightweight and durable. Made from BPA-free plastic.', 
        50, 2, 19, 8, 'https://fluye-statics.s3.amazonaws.com/product_color/Sport_700_Lila_Logo.png', 89.00),
    (7, 'Fluye Cup Pro 590 ml Manu', 
        'Lavar a mano con agua tibia', 
        'Aislante térmico', 
        35, 3, 1, 5, 'https://fluye-statics.s3.amazonaws.com/product_color/Cup_Pro_590_Manu_Logo.png', 89.00),
    (8, 'Fluye Cup Pro 590 ml Maras', 
        'Lavar a mano con agua tibia', 
        'Aislante térmico', 
        45, 3, 6, 5, 'https://fluye-statics.s3.amazonaws.com/product_color/Cup_Pro_590_Maras_Logo.png', 79.00),
    (9, 'Fluye Cup Pro 590 ml Baja Sand', 
        'Lavar a mano con agua tibia', 
        'Aislante térmico', 
        40, 3, 18, 5, 'https://fluye-statics.s3.amazonaws.com/product_color/Cup_Pro_590_Baja_Sand_Logo.png', 79.00),
    (10, 'Fluye Cup Pro 590 ml Navy Blue', 
        'Lavar a mano con agua tibia', 
        'Aislante térmico', 
        30, 3, 8, 5, 'https://fluye-statics.s3.amazonaws.com/product_color/Cup_Pro_590_Navy_Blue_Logo.png', 79.00),
    (11, 'Fluye Cup Pro 590 ml Lemon', 
        'Lavar a mano con agua tibia', 
        'Aislante térmico', 
        20, 3, 3, 5, 'https://fluye-statics.s3.amazonaws.com/product_color/Cup_Pro_590_Lemon_Logo.png', 79.00),
    (12, 'Fluye Ceramic Pro 600 ml Baja Sand', 
        'Lavar a mano con agua tibia', 
        'Aislante térmico', 
        50, 5, 18, 6, 'https://fluye-statics.s3.amazonaws.com/product_color/Ceramic_Pro_600_Baja_Sand_Logo.png', 129.00),
    (13, 'Fluye Ceramic Pro 600 ml Bariloche', 
        'Lavar a mano con agua tibia', 
        'Aislante térmico', 
        45, 5, 11, 6, 'https://fluye-statics.s3.amazonaws.com/product_color/Ceramic_Pro_600_Bariloche_Logo.png', 129.00),
    (14, 'Fluye Ceramic Pro 600 ml Lila', 
        'Lavar a mano con agua tibia', 
        'Aislante térmico', 
        35, 5, 19, 6, 'https://fluye-statics.s3.amazonaws.com/product_color/Ceramic_Pro_600_Lila_Logo.png', 129.00),
    (15, 'Fluye Ceramic Pro 600 ml Navy Blue', 
        'Lavar a mano con agua tibia', 
        'Aislante térmico', 
        25, 5, 8, 6, 'https://fluye-statics.s3.amazonaws.com/product_color/Ceramic_Pro_600_Navy_Blue_Logo.png', 129.00);
-- migrate:down
DELETE FROM productos